[package]
name = "pond-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bbx_dsp = { version = "0.4.2", features = ["ftz-daz", "simd"] }
bbx_net = { version = "0.4.2", features = ["websocket"] }

rodio = "0.20"
tokio = { version = "1", features = ["full"] }
ctrlc = "3.4"
rand = "0.8"
rand_chacha = "0.3"
