[package]
name = "pond-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bbx_dsp = { path = "../../bbx_audio/bbx_dsp", features = ["ftz-daz", "simd"] }
bbx_net = { path = "../../bbx_audio/bbx_net", features = ["websocket"] }
bbx_player = { path = "../../bbx_audio/bbx_player", features = ["rodio"] }

tokio = { version = "1", features = ["full"] }
ctrlc = "3.4"
rand = "0.8"
rand_chacha = "0.3"
